version: 2.1

orbs:
  butterfly-orb: muneeb131/butterflyorb@dev:alpha

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
        - checkout
        - butterfly-orb/scan:
              kubernetes-manifest: "kubernetes-manifest.yaml"
              chkk-access-token: $CHKK_ACCESS_TOKEN
              args:
                continue-on-error