version: 2.1

orbs:
  circleci-orb: muneeb131/butterflyorb@dev:beta

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
        - checkout
        - circleci-orb/scan:
            kubernetes-manifest: "kubernetes-manifest.yaml"
            chkk-access-token: $CHKK_ACCESS_TOKEN